import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import { NavLinks } from "./navigation/nav-links";
import "bootstrap/dist/css/bootstrap.css";
import "../../public/stylesheets/page.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="offset-2 col-lg-8">
          <NavLinks />
          <div className=" container-fluid offset-1 col-md-10 rounded-3 bg-light">
            <main>{children}</main>
          </div>
        </div>
        <footer className="footer offset-2 col-lg-8 py-1 sticky-bottom rounded-3" style={{ backgroundColor: "#f8f9fa" }}>
          <p className="text-center text-muted">©Sukhen Goswami</p>
        </footer>
      </body>
    </html>
  );
}
