import type { Metadata } from "next";
// import "./globals.css";
import { NavLinks } from "./navigation/nav-links";
import "bootstrap/dist/css/bootstrap.css";
import "../../public/stylesheets/page.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="offset-2 col-lg-8">
          <NavLinks />
          <div className=" container-fluid offset-1 col-md-10 rounded-3 bg-light mb-5">
            <main>{children}</main>
          </div>
        </div>
        <footer className="footer offset-2 col-lg-8 py-1 fixed-bottom rounded-3 mt-5" style={{ backgroundColor: "#f8f9fa" }}>
          <p className="text-center text-muted">©Sukhen Goswami</p>
        </footer>
      </body>
    </html>
  );
}
